/home/smaity/Transfer-learning/without-label-V2/kdeClassifier.py:32: RuntimeWarning: invalid value encountered in log
  for Xi in training_sets] + np.log(weights)
